# SPDX-License-Identifier: GPL-3.0-or-later
# Native test tools must belong to the configured Qt installation.
function(holonight_validate_test_tool variable)
    get_filename_component(path "${${variable}}" ABSOLUTE BASE_DIR "${CMAKE_SOURCE_DIR}")
    if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
        message(FATAL_ERROR "${variable} does not name an existing executable: ${path}")
    endif()
    execute_process(COMMAND test -x "${path}" RESULT_VARIABLE status)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "${variable} is not executable: ${path}")
    endif()
    set(${variable} "${path}" PARENT_SCOPE)
endfunction()

if(NOT DEFINED HOLONIGHT_QMLLINT_EXECUTABLE)
    if(TARGET Qt6::qmllint)
        string(TOUPPER "${CMAKE_BUILD_TYPE}" configuration)
        get_target_property(configurations Qt6::qmllint IMPORTED_CONFIGURATIONS)
        set(properties IMPORTED_LOCATION)
        if(configuration)
            list(PREPEND properties "IMPORTED_LOCATION_${configuration}")
        endif()
        foreach(config IN LISTS configurations)
            string(TOUPPER "${config}" config)
            list(APPEND properties "IMPORTED_LOCATION_${config}")
        endforeach()
        foreach(property IN LISTS properties)
            get_target_property(location Qt6::qmllint "${property}")
            if(location AND EXISTS "${location}" AND NOT IS_DIRECTORY "${location}")
                set(HOLONIGHT_QMLLINT_EXECUTABLE "${location}")
                break()
            endif()
        endforeach()
    endif()
    if(NOT DEFINED HOLONIGHT_QMLLINT_EXECUTABLE)
        message(FATAL_ERROR "Configured Qt has no usable Qt6::qmllint location. Install its QML tools or set HOLONIGHT_QMLLINT_EXECUTABLE to an executable path.")
    endif()
endif()
holonight_validate_test_tool(HOLONIGHT_QMLLINT_EXECUTABLE)

if(NOT DEFINED HOLONIGHT_QML_EXECUTABLE)
    get_filename_component(tool_directory "${HOLONIGHT_QMLLINT_EXECUTABLE}" DIRECTORY)
    if(IS_ABSOLUTE "${QT6_INSTALL_BINS}")
        set(binary_directory "${QT6_INSTALL_BINS}")
    elseif(QT6_INSTALL_BINS AND QT6_INSTALL_PREFIX)
        set(binary_directory "${QT6_INSTALL_PREFIX}/${QT6_INSTALL_BINS}")
    else()
        set(binary_directory "")
    endif()
    # Separate searches ensure a sibling wins even when the bins directory has qml6.
    foreach(directory IN ITEMS "${tool_directory}" "${binary_directory}")
        if(directory)
            find_program(discovered_qml NAMES qml6 qml PATHS "${directory}" NO_DEFAULT_PATH NO_CACHE)
            if(discovered_qml)
                set(HOLONIGHT_QML_EXECUTABLE "${discovered_qml}")
                break()
            endif()
        endif()
    endforeach()
    if(NOT DEFINED HOLONIGHT_QML_EXECUTABLE)
        message(FATAL_ERROR "Configured Qt has no qml runner beside qmllint or in its binary directory. Install its QML tools or set HOLONIGHT_QML_EXECUTABLE to an executable path.")
    endif()
endif()
holonight_validate_test_tool(HOLONIGHT_QML_EXECUTABLE)
