// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Andrii L <lebeden@gmail.com>
#include "hninputinteraction.h"

#include <QCursor>
#include <QKeyEvent>
#include <QMouseEvent>
#include <QQuickItem>
#include <QQuickWindow>
#include <QWheelEvent>

namespace {
bool isModifier(int key) {
  switch (key) {
    case Qt::Key_Shift:
    case Qt::Key_Control:
    case Qt::Key_Meta:
    case Qt::Key_Alt:
    case Qt::Key_AltGr:
    case Qt::Key_CapsLock:
    case Qt::Key_NumLock:
    case Qt::Key_ScrollLock:
      return true;
    default:
      return false;
  }
}
}  // namespace

// A window owns its observer; attached objects only subscribe to that observer.
// No application-global input authority and no dependency on Quick Controls.
class HnWindowInputState : public QObject {
  Q_OBJECT
 public:
  explicit HnWindowInputState(QQuickWindow* window)
      : QObject(window), window_(window), screen_position_(QCursor::pos()) {
    window->installEventFilter(this);
  }

  [[nodiscard]] bool hoverAllowed() const { return hover_allowed_; }
  void suppressHover() { setHoverAllowed(false); }

 signals:
  void hoverAllowedChanged();
  void pointerMoved(QPointF scenePosition);

 protected:
  bool eventFilter(QObject* watched, QEvent* event) override {
    if (watched != window_) {
      return false;
    }
    switch (event->type()) {
      case QEvent::KeyPress:
        if (!isModifier(static_cast<QKeyEvent*>(event)->key())) {
          suppressHover();
        }
        break;
      case QEvent::MouseMove: {
        const auto* mouse = static_cast<QMouseEvent*>(event);
        const auto position = mouse->globalPosition();
        if (position != screen_position_) {
          screen_position_ = position;
          setHoverAllowed(true);
          emit pointerMoved(window_->mapFromGlobal(position));
        }
        break;
      }
      case QEvent::MouseButtonPress:
      case QEvent::MouseButtonRelease:
      case QEvent::MouseButtonDblClick:
        screen_position_ = static_cast<QMouseEvent*>(event)->globalPosition();
        break;
      case QEvent::Wheel:
        screen_position_ = static_cast<QWheelEvent*>(event)->globalPosition();
        break;
      default:
        break;
    }
    // HoverEnter/HoverMove can be generated by layout and scrolling. Only the
    // window's mouse movement with changed screen coordinates grants authority.
    return false;
  }

 private:
  void setHoverAllowed(bool value) {
    if (hover_allowed_ == value) {
      return;
    }
    hover_allowed_ = value;
    emit hoverAllowedChanged();
  }

  QQuickWindow* window_;
  QPointF screen_position_;
  bool hover_allowed_ = true;
};

HnInputInteraction::HnInputInteraction(QObject* parent) : QObject(parent) {
  if (auto* item = qobject_cast<QQuickItem*>(parent)) {
    connect(item, &QQuickItem::windowChanged, this, &HnInputInteraction::setWindow);
    setWindow(item->window());
  } else {
    setWindow(qobject_cast<QQuickWindow*>(parent));
  }
}

HnInputInteraction* HnInputInteraction::qmlAttachedProperties(QObject* object) {
  return new HnInputInteraction(object);
}

bool HnInputInteraction::hoverAllowed() const { return state_ && state_->hoverAllowed(); }

void HnInputInteraction::suppressHover() {
  if (state_) {
    state_->suppressHover();
  } else {
    pending_suppression_ = true;
  }
}

void HnInputInteraction::setWindow(QQuickWindow* window) {
  if (state_) {
    disconnect(state_, nullptr, this, nullptr);
  }
  state_ = nullptr;
  if (window != nullptr) {
    state_ = window->findChild<HnWindowInputState*>(QString(), Qt::FindDirectChildrenOnly);
    if (!state_) {
      state_ = new HnWindowInputState(window);
    }
    connect(state_, &HnWindowInputState::hoverAllowedChanged, this, &HnInputInteraction::hoverAllowedChanged);
    connect(state_, &HnWindowInputState::pointerMoved, this, &HnInputInteraction::pointerMoved);
    connect(state_, &QObject::destroyed, this, &HnInputInteraction::hoverAllowedChanged);
    if (pending_suppression_) {
      pending_suppression_ = false;
      state_->suppressHover();
    }
  }
  emit hoverAllowedChanged();
}

#include "hninputinteraction.moc"
